version: '3'
services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "inventory_system"
      MYSQL_USER: "safwan"
      MYSQL_PASSWORD: "safwan@123"
    ports:
      - "3306:3306"
